/**
 * MiroFish scenario simulation adapter.
 * Repo: https://github.com/666ghj/MiroFish
 * Architecture: multi-agent LLM system — graph construction, entity extraction,
 *   persona generation, forward simulation → narrative prediction report.
 *
 * Runtime modes:
 *   1. Self-hosted:  set MIROFISH_API_URL=http://localhost:5001  (MiroFish backend)
 *   2. Offline:      returns null (graceful degradation — caller ignores qualitative signal)
 *
 * Usage: feed in earnings reports, news headlines, macro data as seed material.
 * MiroFish simulates multiple agent interactions and returns a scenario with
 * a directional bias that we map to a [-1, 1] sentiment score.
 */

export interface MiroFishScenario {
  symbol: string
  /** Narrative scenario text generated by MiroFish agents */
  scenario_text: string
  /** Bull/bear/neutral label extracted from the report */
  outlook: 'bullish' | 'bearish' | 'neutral'
  /** Mapped sentiment score: bullish=+1, neutral=0, bearish=-1 */
  sentiment_score: number
  /** [0,1] confidence estimated from agent consensus */
  confidence: number
  /** Raw MiroFish report object (passed through for UI display) */
  raw_report?: Record<string, unknown>
  source: 'mirofish-api' | 'unavailable'
}

/** Seed material sent to MiroFish */
export interface MiroFishInput {
  symbol: string
  /** Financial news headlines or earnings excerpts */
  news_items?: string[]
  /** Analyst report text */
  analyst_notes?: string
  /** Macro context (GDP, inflation, rates) */
  macro_context?: string
  /** How many days forward to simulate */
  forecast_days?: number
}

/** Shape returned by MiroFish /api/predict endpoint */
interface MiroFishApiResponse {
  report_text: string
  outlook?: 'bullish' | 'bearish' | 'neutral'
  confidence?: number
  raw_report?: Record<string, unknown>
}

// ─── Outlook extraction ───────────────────────────────────

function extractOutlook(text: string): 'bullish' | 'bearish' | 'neutral' {
  const lower = text.toLowerCase()
  const bullSignals = (lower.match(/\b(bullish|upside|rally|outperform|buy|positive|growth|surge)\b/g) ?? []).length
  const bearSignals = (lower.match(/\b(bearish|downside|decline|underperform|sell|negative|contraction|fall|drop)\b/g) ?? []).length
  if (bullSignals > bearSignals + 1) return 'bullish'
  if (bearSignals > bullSignals + 1) return 'bearish'
  return 'neutral'
}

function outlookToScore(outlook: 'bullish' | 'bearish' | 'neutral'): number {
  return outlook === 'bullish' ? 1 : outlook === 'bearish' ? -1 : 0
}

// ─── HTTP helper ──────────────────────────────────────────

async function callMiroFishApi(input: MiroFishInput): Promise<MiroFishScenario | null> {
  const baseUrl = process.env.MIROFISH_API_URL
  if (!baseUrl) return null

  const seedMaterial = [
    input.analyst_notes,
    input.macro_context,
    ...(input.news_items ?? []),
  ]
    .filter(Boolean)
    .join('\n\n')

  if (!seedMaterial.trim()) return null

  try {
    const res = await fetch(`${baseUrl}/api/predict`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        symbol: input.symbol,
        seed_material: seedMaterial,
        forecast_days: input.forecast_days ?? 30,
      }),
      signal: AbortSignal.timeout(60_000), // MiroFish runs multi-agent sims — allow 60s
    })
    if (!res.ok) return null
    const data: MiroFishApiResponse = await res.json()

    const outlook = data.outlook ?? extractOutlook(data.report_text)
    return {
      symbol: input.symbol,
      scenario_text: data.report_text,
      outlook,
      sentiment_score: outlookToScore(outlook),
      confidence: data.confidence ?? 0.5,
      raw_report: data.raw_report,
      source: 'mirofish-api',
    }
  } catch {
    return null
  }
}

// ─── Public API ───────────────────────────────────────────

/**
 * Get a qualitative scenario forecast for a symbol.
 * Returns null if MiroFish is not configured — callers should treat null
 * as "no qualitative signal available" and rely on quantitative signals only.
 *
 * @example
 *   const scenario = await miroFishPredict({
 *     symbol: 'NVDA',
 *     news_items: ['NVDA beats earnings by 15%', 'Data center revenue +220% YoY'],
 *     macro_context: 'Fed held rates steady; AI capex cycle accelerating',
 *   })
 *   if (scenario) console.log(scenario.outlook, scenario.sentiment_score)
 */
export async function miroFishPredict(input: MiroFishInput): Promise<MiroFishScenario | null> {
  return callMiroFishApi(input)
}

/**
 * Combine a Kronos quantitative score with a MiroFish qualitative score
 * into a single blended signal.
 *
 * @param kronosScore  Expected return fraction from Kronos (e.g. 0.023)
 * @param miroScore    MiroFish sentiment_score (-1, 0, +1) or null
 * @param miroConfidence  MiroFish confidence [0,1] or null
 * @param kronosWeight Weight for Kronos score [0,1]; MiroFish gets (1 - weight)
 * @returns Blended score in [-1, 1] range
 */
export function blendSignals(
  kronosScore: number,
  miroScore: number | null,
  miroConfidence: number | null,
  kronosWeight = 0.7
): number {
  // Normalise kronos expected_return to [-1, 1] — clamp at ±10%
  const kronosNorm = Math.max(-1, Math.min(1, kronosScore / 0.1))

  if (miroScore === null) return kronosNorm

  const miroWeight = (1 - kronosWeight) * (miroConfidence ?? 0.5)
  const adjustedKronosWeight = 1 - miroWeight

  return adjustedKronosWeight * kronosNorm + miroWeight * miroScore
}
